### ISSUE TITLE
MagnumSdl2Application not linked on windows when with_sdl2application=True

### ISSUE THREAD

**Issue by helmesjo** [helmesjo/conan-magnum#1]
It's missing in the `Findmagnum.cmake` (using `cmake_find_package` generator), but it is in the `conanmanifest.txt`.

Consistent between Debug/Release & x86/x86_64.

**Comment by mosra** [comment]
Btw., the `*Application` classes are *always* built statically (unlike all the other libs where it is configurable), so maybe this is related?

**Comment by helmesjo** [comment]
Don't think so... I'm not too high on the details of conan, but the information for all libs (or files in general) is kept in the conan-magnum package (listed in the file called `conanmanifest.txt`), ~~which is used by the [`cmake_find_package`](https://docs.conan.io/en/latest/integrations/cmake/cmake_find_package_generator.html) to generate `Find<package>.cmake` files for all dependencies (not sure where the [specified order](https://github.com/helmesjo/conan-magnum/blob/95b44de4c853c9f90142c28c6043d79d41e13ae3/conanfile.py#L256-L285) is determined).~~ For some reason it skips `lib/MagnumSdl2Application.lib`, it is missing in the `Findmagnum.cmake` file.

Anyways, created the issue just as a reminder, as I can't look into this atm. It might very well be something obvious & wrong in the recipe.

**Edit 1**
Actually, it could be that the [`package_info`](https://github.com/helmesjo/conan-magnum/blob/95b44de4c853c9f90142c28c6043d79d41e13ae3/conanfile.py#L254) method is invoked at the time a package is "used" (eg. generating the `Findmagnum.cmake`). Can't find details about this in the [docs](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info), but it would make sense as I can't find this "link order" info in the package elsewhere except in the `conanfile.py`.

**Edit 2**
Okay, just confirmed that this is the case. So my recipe is failing to include `MagnumSdl2Application` for some reason.

**Comment by helmesjo** [comment]
Hehe... I was [missing a comma](https://github.com/helmesjo/conan-magnum/blob/95b44de4c853c9f90142c28c6043d79d41e13ae3/conanfile.py#L279), so `MagnumSdl2Application` & `MagnumWindowlessSdl2Application` got mushed into `MagnumSdl2ApplicationMagnumWindowlessSdl2Application` which of course didn't match any of the built libs. 🙃 

Fixed in 60c76c5d9879cdc2a4f884313579571bf28e5983.
