### ISSUE TITLE
Update for version 2019.1

### ISSUE THREAD

**Issue by xeoneux** [helmesjo/conan-magnum#4]
Hi, thanks for creating a conan package for magnum 😄 
When will the package be updated for version 2019.1?

**Comment by helmesjo** [comment]
Hi! 
I'll give it a go and we'll see! :blush: (within a few days at least should be possible, away atm)

**Comment by mosra** [comment]
While we are at it, @helmesjo, is there anything I can do for moving mosra/magnum#304 forward? :)

**Comment by helmesjo** [comment]
@mosra Not sure yet, I've been off it for some time... But I'll check it out in the coming days/week and holla at you! 👌😊

**Comment by Croydon** [comment]
Just to throw my two cents into the mix: I didn't forget that I promised to help to carry an official Conan recipe for magnum forward. I'm just extremely busy every since 😓 

@mosra Do you have a rough idea when you will make a new stable release for magnum?

**Comment by mosra** [comment]
We are all extremely busy all the time, no worries ;) 

I'm doing a university lecture that involves Magnum on May 15th, so roughly the week before I'd like to release a new stable version so the students have a fresh tested thing to play with. Is that timeline feasible for you?

**Comment by Croydon** [comment]
I guess so. And the sooner the better, than I can cross off another thing from my to do list 😄 

@mosra Could you please have a look at this option list and tell me if any of these got removed for 2019.01 or if new got added which are missing? https://github.com/helmesjo/conan-magnum/blob/636125cc4620a1db38e9acd457e6c0d05b66f424/conanfile.py#L41

**Comment by mosra** [comment]
All options that were deprecated (and are removed now) are already gone from this list (we did that during our initial discussion on mosra/magnum#304 IIRC), so all good :)
