### ISSUE TITLE
Installation requires user

### ISSUE THREAD

**Issue by mscofield0** [helmesjo/conan-magnum#5]
> ```
> Please log in to "helmesjo" to perform this action. Execute "conan user" command.
> ```

How do I bypass this?

**Comment by helmesjo** [comment]
Given that bintray was _sunset_ and replaced by jfrog artifactory, you need to change the repository url. The new url is `https://helmesjo.jfrog.io/artifactory/api/conan/public-conan`.
The readme is wrong (sorry for that), but I'll change it!

**Comment by mscofield0** [comment]
Ah thanks, I'll close this now.
