### ISSUE TITLE
Emscripten support and conan center

### ISSUE THREAD

**Issue by werto87** [helmesjo/conan-magnum#6]
Hi helmesjo,

I want to add your receipt to the conan center and exctend it with emscripten support.
Is this okay for you?

**Comment by helmesjo** [comment]
Hi!
Of course, go right ahead! Though you might want to take a peek [here](https://github.com/mosra/magnum/issues/304), where it's been in the works for a while 😇

**Comment by werto87** [comment]
I do not see a problem here. I will add emscripten support for corrade and magnum in conan center.

**Comment by werto87** [comment]
Another topic:
I have a project which is only relevant in my client server applications.
I wrote a receipt for it. Do you know how to handle header only project which are useless for others?

**Comment by helmesjo** [comment]
No sorry, I haven't been packaging stuff for a year or so, so I have not followed all that's new. But ask on conan-center and I'm sure you'll get the help you need!

**Comment by jgsogo** [comment]
Hi, @werto87 and @helmesjo , what is the status of this? I was looking for something WASM+3D related and I think magnum could be one of the best approaches. IMHO migrating this recipe to `conan-center-index` can be very interesting: it will get more feedback, contributions and enhancements from the community and the binaries will be available via ConanCenter. Are there missing dependencies? Is there anything preventing us from opening that pull-request?

Thanks!

**Comment by helmesjo** [comment]
No status, I haven't touched it in quite some time.
I'd say the main issue are all the system dependencies which are generally disliked in `conan-center`.

Work has been done but appears to have stagnated.
https://github.com/mosra/magnum/issues/304

**Comment by werto87** [comment]
Hi jgsogo, I finished an package for emscripten as build_require and I packaged corrade, magnum and magnum-integration. I am currently working on bringing them to conan. You can use my git_lab page "https://gitlab.com/werto87/conan-the-example". Here you can find a short guide to build for emscripten and the recipes for emscripten as build_require and corrade, magnum and magnum-integration and some other recipes. Try the recipes here "https://gitlab.com/werto87/conan-the-example/-/packages".
current state in bringing magnum to emscripten: "https://github.com/conan-io/conan-center-index/pull/6163".
Note: I only tested this on arch linux

**Comment by jgsogo** [comment]
> I'd say the main issue are all the system dependencies which are generally disliked in `conan-center`.

Yes, we indeed don´t like system dependencies if they can be actual libraries... but there are already some recipes that use system-installed binaries. You can grep for `system` as version, for example in `opengl/system` ([link](https://github.com/conan-io/conan-center-index/tree/master/recipes/opengl/all)). If it makes sense, we can add more _system_ recipes.

@werto87 , I tried [a recipe for `emsdk` some time ago](https://github.com/conan-io/conan-center-index/pull/4860), but unfortunately I didn't have time to improve it. I'll have a look to yours, but anyway, I'll try to focus first on bringing Magnum to CCI with native builds... we will have time to think about emscripten in ConanCenter (and we will).

Disclaimer: I'm JFrog's staff working in ConanCenter 🎉

**Comment by werto87** [comment]
~~Please note that I have improved helmesjo magnum recipe you can take a look at git hub "https://github.com/werto87/conan_magnum" there is also the corrade and the magnum-integration. I am fine if you take them to  conan.~~
Edit: forget this if you are not interestet in emscripten magnum

**Comment by jgsogo** [comment]
Sure I'm interested, but first I will work on the recipe for native builds, and then I will have a look to cross-building and emsdk builds. Step by step.

**Comment by werto87** [comment]
Ah, okay know I understand you @jgsogo.

**Comment by werto87** [comment]
@jgsogo What is the status on magnum with conan? My old recipe has a problem (using magnum plugins) and I gave up on making magnum work with the sources of the official magnum repo. I am working on rebuilding magnum without findCmake. I try to get all dependencies from conan.

**Comment by jgsogo** [comment]
Almost there: https://github.com/conan-io/conan-center-index/pull/7095. Fine-tunning pending.

I have also recipes for the plugins and integrations (of course, not all of them, there are some missing packages for some integrations) that I'll submit after `magnum` itself.

**Comment by werto87** [comment]
Thank you for the information. I will take a look.

**Comment by werto87** [comment]
@jgsogo  Do you create an extra package for integrations and plugins? Do you add them as optional requirement for magnum? or is magnum a requirement for integrations and plugins?

**Comment by jgsogo** [comment]
Those will be extra packages, I think it is expected as they are developed in independent repositories. And, yes, `magnum` will be a requirement for those two other recipes.

**Comment by werto87** [comment]
I think it could be hard to build plugins and integration together. I  want to bring up the idea of building everything in the magnum recipe. I am looking forward to your recipe and use magnum with integration plugins and emscripten. No mater which way you take I wish you good luck and strong nerves.

**Comment by jgsogo** [comment]
I'm finding it hard to orchestrate the huge amount of options and dependencies/requirements between them. That's the main issue, but so far I'm building the libraries and consuming the 3rd parties using Conan packages

**Comment by weyrick** [comment]
Hello, it seems a dependency of this work has created a breaking change: https://github.com/conan-io/conan-center-index/pull/6290 is causing failures. I suspect it is due to this change: https://github.com/conan-io/conan-center-index/commit/e0a2f0860bdda3a19533c2135c76b8cf6c5318a6#diff-6cbddb4afca2b02007a8d05873301d528869bd0427481eea5e21bad1b360fc41R104 which removes the final 'Corrade' from the path. Failure in my CI looks like this: https://github.com/ns1labs/pktvisor/runs/3489223181?check_suite_focus=true ... pinning the previous recipe fixes it.

**Comment by jgsogo** [comment]
@weyrick , please, submit the issue to https://github.com/conan-io/conan-center-index repository, that's the place where you will get better help. 

Quick comments:
 * You should use revisions _always_, like you did in https://github.com/ns1labs/pktvisor/pull/116, Conan recipes keep evolving (improving), and breaking changes are expected. We try to work always in the right direction, but you know C++ building is never easy.
 * I'm not sure what you mean by _final Corrade_. In the project I can see `corrade-rc` executable when building `with_utility=True`

**Comment by weyrick** [comment]
Ok, will do, thanks.

By "final" I meant the diff in the line I referenced:
```
self.copy("UseCorrade.cmake", src=share_cmake, dst=os.path.join(self.package_folder, "lib", "cmake", "Corrade"))
```
changed to
```
self.copy("UseCorrade.cmake", src=share_cmake, dst=os.path.join(self.package_folder, "lib", "cmake"))
```
